definitions:
  models.Language:
    description: Language model for storing programming languages in the database.
    properties:
      description:
        type: string
      name:
        type: string
    type: object
info:
  contact:
    email: adrienpani@gmail.com
    name: Adrien Panis
  description: API for managing a list of programming languages.
  title: Language List API
  version: "1.0"
paths:
  /languages:
    get:
      consumes:
      - application/json
      description: Retrieve a list of all programming languages
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Language'
            type: array
        "500":
          description: Internal Server Error
      summary: Get all programming languages
      tags:
      - languages
    post:
      consumes:
      - application/json
      description: Add a new programming language to the list
      parameters:
      - description: Language object
        in: body
        name: language
        required: true
        schema:
          $ref: '#/definitions/models.Language'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Language'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Add a new programming language
      tags:
      - languages
  /languages/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve a programming language by its ID
      parameters:
      - description: Language ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Language'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get a programming language by ID
      tags:
      - languages
swagger: "2.0"
